// <auto-generated />
using System;
using IPS.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IPS.DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20231009082538_Initial3")]
    partial class Initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IPS.DAL.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IPSId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IPSId");

                    b.ToTable("Cargoes");
                });

            modelBuilder.Entity("IPS.DAL.IPS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Square")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("iPs");
                });

            modelBuilder.Entity("IPS.DAL.IPS2Cargo", b =>
                {
                    b.Property<int>("IPSId")
                        .HasColumnType("int");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.HasKey("IPSId", "CargoId");

                    b.HasIndex("CargoId");

                    b.ToTable("IPS2Cargo");
                });

            modelBuilder.Entity("IPS.DAL.Cargo", b =>
                {
                    b.HasOne("IPS.DAL.IPS", null)
                        .WithMany("Cargos")
                        .HasForeignKey("IPSId");
                });

            modelBuilder.Entity("IPS.DAL.IPS2Cargo", b =>
                {
                    b.HasOne("IPS.DAL.Cargo", "Cargo")
                        .WithMany("IPS2Cargoes")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPS.DAL.IPS", "IPS")
                        .WithMany("IPS2Cargoes")
                        .HasForeignKey("IPSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
